name: Adds issues with "open" label to GitHub project
on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add issues with "open" label to GitHub project
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/OpenLiberty/projects/18
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: open
